addons:
apt:
update: true

env:
    - TASK_DIR=task_02

stages:
  - stylecheck
  - memcheck
  - test

language: cpp

before_install:
    - sudo apt update
    - sudo apt install clang-format-${CLANG_VERSION} -version || true
    - sudo apt install valgrind
    - sudo apt install cmake
    - sudo apt install cppcheck
    - sudo apt install libgtest-dev
    - cd /usr/src/gtest
    - sudo cmake .
    - sudo make
    - sudo cp *.a /usr/lib
    - cd -

before_script:
    - cd $TASK_DIR
    - cmake CMakeLists.txt
    - make
    
jobs:
  include:
    - stage: stylecheck
      before_script: skip
      script: cppcheck --std=c++11 -q --enable=all --error-exitcode=1 .
      
    - stage: memcheck
      script: valgrind --tool=memcheck --leak-check=full -q ./main.exe

    - stage: test
      script: ctest --output-on-failure
      after_script: make clean